### ISSUE TITLE
on using the epics.wx widgets

### ISSUE THREAD

**Issue by dmichel76** [pyepics/epicsapps#17]
Just trying it out with a very simple:

```
import wx
import epics.wx

app = wx.App()

frame = wx.Frame(None, -1, 'simple.py')
panel = wx.Panel(frame, -1)
epics.wx.PVText(panel, pv="MY:PV")
frame.Show()

app.MainLoop()
```

But nothing is displayed... probably missing something trivial here, but what?

**Comment by newville** [comment]
@dmichel76  I think the problem here is not naming (and so keeping a reference) to the PVText object.  That is, this should work:

```python
import wx
import epics.wx

app = wx.App()

frame = wx.Frame(None, -1, 'simple.py')
panel = wx.Panel(frame, -1)

# save name so that PVText does not get garbage collected
pvtext = epics.wx.PVText(panel, pv="MY:PV")

frame.Show()
app.MainLoop()
```

Of course, for anything more complicated, you'll want to use wx  sizers to control placement of things.  It may even be that on some systems (or some versions of wxPython) that using sizers to explicitly place the widgets on the Panel is important.

**Comment by dmichel76** [comment]
Hi @newville, Just tried that but didn't work :-(

version of wx is 4.0.0b2 msw (phoenix)
version of pyepics is 3.3.0
running on Windows 10

If I replace the epics.wx.PVText with a wx.StaticText, it works fine...

**Comment by newville** [comment]
@dmichel76  Can you clarify "didn't work"?  That's not very specific.   Did any window show up? 

The example did work for me though I'm not able to test on Windows 10 (only on Mac OSX) at the moment.

Again, it might be necessary to use sizers to place widgets on to a panel and then onto a frame might.  I think it would be only trivial examples that could every really be useful without using sizers. That said, I don't know why that would be needed for a StaticText and not a PVText (which is a subclass of StaticText).

**Comment by dmichel76** [comment]
@newville, the main window app shows up, yes. No warnings/errors on the command line. There is simply no string being displayed, as if there was not StaticText widget at all.

I'll try using sizers to see what happens.... I knew that it's subclass of StaticText. That's why I tried it and mentioned it on here - would interesting to find out why it works for a STaticText and not for the PVText in such a simple example code.

**Comment by dmichel76** [comment]
OK, got nowhere so uninstalled and reinstalled pyepics... and then it worked as expected! A bit weird, but clearly it's not a problem you have to worry about... False alarm!

**Comment by newville** [comment]
@dmichel76  OK, weird but better that it works!
